In [5]:
import numpy as np

def NN(x1, x2, w1, w2, b):
    yin = x1*w1+x2*w2+b
    return sigmoid(yin)

def sigmoid(x):
    return 1/(1+np.exp(-x))

NN(1,0,1,1,1)


0.8807970779778823

In [28]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivation(x):
    return x*(x-1)

input = np.array([[0,0,1],
                  [1,1,1],
                  [1,0,1],
                  [0,1,0]])

output = np.array([[0,1,1,0]]).T

np.random.seed(1)

weights = 2* np.random.random((3,1))-1

print('Initial weights are:')
print(weights)

for i in range(100000):
    input_layer = input
    o_output = sigmoid(np.dot(input_layer, weights))

    loss = o_output - output
    
    adjustment = loss * sigmoid_derivation(o_output)
    
    weights = weights + np.dot(input_layer.T, adjustment)
    
print('new weights are')
print(weights)

print('obtainrd output vlaues are')
print(o_output)

Initial weights are:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
new weights are
[[16.33455471]
 [-5.39659002]
 [-5.39657949]]
obtainrd output vlaues are
[[0.00451163]
 [0.9960942 ]
 [0.99998223]
 [0.00451159]]


In [7]:
input

array([[1, 1],
       [1, 0],
       [0, 1],
       [0, 0]])

In [12]:
output

array([[1],
       [0],
       [0],
       [0]])