In [10]:
import numpy as np
x = np.array(([2, 9],[1, 5],[3, 6]),dtype=float)
y = np.array(([92],[86],[89]), dtype=float)

In [11]:
x

array([[2., 9.],
       [1., 5.],
       [3., 6.]])

In [12]:
y

array([[92.],
       [86.],
       [89.]])

In [22]:
epoch=1
lr=0.1
in_nu = 2
hidd_nu = 4
out_nu = 1 

In [31]:
X = x/np.amax(x)

In [32]:
np.amax(x)

1.0

In [15]:
np.amax(y)

92.0

In [16]:
y = y/100

In [18]:
np.random

<module 'numpy.random' from 'C:\\Users\\PC2020\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [24]:
weight_hidd=np.random.uniform(size=(in_nu,hidd_nu))
weight_out = np.random.uniform(size=(hidd_nu, out_nu))
bias_hidd = np.random.uniform(size=(1,hidd_nu))
bias_out = np.random.uniform(size=(1, out_nu))

In [37]:
bias_hidd = np.random.uniform(size=(1,hidd_nu))

bias_hidd

array([[0.44611583, 0.03079355, 0.43799614, 0.94126242]])

In [25]:
weight_hidd=np.random.uniform(size=(in_nu,hidd_nu))

weight_hidd

array([[0.69924336, 0.40090395, 0.8210659 , 0.54509063],
       [0.57434807, 0.29644908, 0.98802554, 0.72249655]])

In [26]:
x

array([[0.22222222, 1.        ],
       [0.11111111, 0.55555556],
       [0.33333333, 0.66666667]])

In [29]:
for i in range(epoch):
    hidd_in=np.dot(x,weight_hidd) + bias_hidd
    hidd_act = sigmoid(hidd_in)
    out_in=np.dot(hidd_act,weight_out) + bias_out
    out = sigmoid(out_in)


In [28]:
def sigmoid (x):
    return 1/1 + np.exp(-x)

In [33]:
print("input: \n" +str(X))

input: 
[[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]]


In [35]:
print("Predicted Output :" ,out)

Predicted Output : [[1.02747849]
 [1.02042614]
 [1.02462236]]


In [36]:
print("Actual output: \n" + str(y))

Actual output: 
[[0.92]
 [0.86]
 [0.89]]
