In [11]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt 
from sklearn import tree, metrics, model_selection, preprocessing

In [12]:
df = pd.read_csv('iris.csv')
df.head(5)

sepal.length  sepal.width  petal.length  petal.width species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [13]:
df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

array([0, 1, 2], dtype=int64)

In [14]:
y = df['species_label']
X = df[['sepal.length', 'sepal.width','petal.length','petal.width']] 

In [72]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,test_size=0.1, random_state=0)

In [73]:
dtree = tree.DecisionTreeClassifier(criterion='gini', max_depth=6)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=6)

In [74]:
y_pred = dtree.predict(X_test)

In [75]:
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Accuracy: 1.00


In [76]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[3 0 0]
 [0 8 0]
 [0 0 4]]


In [2]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt 
from sklearn import tree, metrics, model_selection, preprocessing

df = pd.read_csv('iris.csv')
df.head(5)

df['species_label'],i = pd.factorize(df['species'])
df['species'].unique()
df['species_label'].unique()

y = df['species_label'] 
X = df[['sepal.length', 'sepal.width']] 

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y,test_size=0.3, random_state=0)

dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
dtree.fit(X_train, y_train)

y_pred = dtree.predict(X_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.67
[[16  0  0]
 [ 1  5 12]
 [ 0  2  9]]


In [78]:
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=6)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6)

In [79]:
X = df[['sepal.length', 'sepal.width']] 

In [80]:
accuracy = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Accuracy: 1.00
